name: My first action
on:
  push
jobs:
  my-first-action:
    runs-on: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set permissions and copy files
        run: |
          sudo chmod -R 777 /var/www/html  # Grant full access (adjust for security)
          sudo cp -rf $GITHUB_WORKSPACE/templatemo_580_woox_travel/* /var/www/html/

      - name: Restart Nginx
        run: sudo systemctl restart nginx

